#!/bin/sh
# Update the Plant Trait Ontology to.obo file, which is in GitHub.
cd plant-trait-ontology
git checkout to.obo
git pull
cd -
echo "*** remove import: lines from to.obo -- they crash the obo loader! ***"
