#!/bin/bash
# Update the crop-ontology files.
# Uses robot to convert the downloaded OWL/RDF file to OBO format.

mkdir -p crop-ontology
for crop in 335 336 337 338 340 341 346
do
    wget https://cropontology.org/ontology/CO_$crop/rdf -O CO_$crop.owl
    java -jar jar/robot.jar convert --check false -i CO_$crop.owl --format obo -o CO_$crop.tmp
    sed s/CO:$crop/CO_$crop/g CO_$crop.tmp > CO_$crop.obo
done
mv CO_*.obo crop-ontology/
rm CO_*.owl
rm CO_*.tmp

echo "*** Remove name: entry at top of files - it breaks the obo loader! ***"
