#!/bin/sh
# Update the Plant Reactome genes to pathways and species file.

mkdir -p plant-reactome
wget https://plantreactome.gramene.org/download/current/gene_ids_by_pathway_and_species.tab
mv gene_ids_by_pathway_and_species.tab plant-reactome/
